name: Security - Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: "20 17 * * *"

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    timeout-minutes: 480
    steps:
      # v5.0.0
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP }}
